# Generated by Django 2.2.7 on 2019-12-16 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOutInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=30)),
                ('set_count', models.CharField(max_length=30)),
                ('break_time', models.CharField(max_length=30)),
                ('excercise', models.CharField(choices=[('PL', 'Plank'), ('SU', 'SitUp'), ('PU', 'PushUp')], max_length=1)),
                ('activity_time', models.DateTimeField(auto_now_add=True)),
                ('completion', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Biometrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=30)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.User')),
            ],
        ),
    ]
